package com.casemanager.newbusiness;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class manulifeObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "sourceOfBusiness")
	private java.lang.String sourceOfBusiness;
	@org.kie.api.definition.type.Label(value = "basicSumAssured")
	private java.lang.Integer basicSumAssured;
	@org.kie.api.definition.type.Label(value = "priority")
	private java.lang.Integer priority;

	public manulifeObject() {
	}

	public java.lang.String getSourceOfBusiness() {
		return this.sourceOfBusiness;
	}

	public void setSourceOfBusiness(java.lang.String sourceOfBusiness) {
		this.sourceOfBusiness = sourceOfBusiness;
	}

	public java.lang.Integer getBasicSumAssured() {
		return this.basicSumAssured;
	}

	public void setBasicSumAssured(java.lang.Integer basicSumAssured) {
		this.basicSumAssured = basicSumAssured;
	}

	public java.lang.Integer getPriority() {
		return this.priority;
	}

	public void setPriority(java.lang.Integer priority) {
		this.priority = priority;
	}

	public manulifeObject(java.lang.String sourceOfBusiness,
			java.lang.Integer basicSumAssured, java.lang.Integer priority) {
		this.sourceOfBusiness = sourceOfBusiness;
		this.basicSumAssured = basicSumAssured;
		this.priority = priority;
	}

}